# Numpy - Numerical Python

In [1]:
import numpy as np

### Numpy array - Array is homogeneous

In [15]:
a = np.array([[1,2,3],[6,7,8]])

In [20]:
print(a)
print('Dimension: ',a.ndim) #No. of dimensions
print('Size: ',a.size) #Size
print('Type: ',a.dtype) #Data Type
#print('Shape: ',a.shape) #Shape

[[1 2 3]
 [6 7 8]]
Dimension:  2
Size:  6
Type:  int32
Shape:  (2, 3)


In [69]:
#(3,2,2)
b = np.array(
    [
        [
            [1,2],
               [3,4]
        ],
        [
            [1,2],
               [3,4]
        ],
        [
            [1,2],
            [3,4]
        ]
             ])
print('Dimension: ',b.ndim) #No. of dimensions
print('Size: ',b.size) #Size
print('Type: ',b.dtype) #Data Type
print('Shape: ',b.shape) #Shape

Dimension:  3
Size:  12
Type:  int32
Shape:  (3, 2, 2)


In [66]:
#(2,3,4)
C = np.array([
        [[1,2,3,4],
         [1,2,3,4],
         [1,2,3,4]],
        [[1,2,3,4],
         [1,2,3,4],
         [1,2,3,4]]])
print(C.shape)

(2, 3, 4)


In [80]:
np.arange(80).reshape(2,2,20)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
         56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
         76, 77, 78, 79]]])

In [81]:
np.arange(100).reshape(2,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [90]:
print(np.arange(10,80,20))

[10 30 50 70]


In [94]:
np.zeros((3,5)) # Creates an array full of zeroes

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [96]:
a = np.array([3.0,5.0,6])
a

array([ 3.,  5.,  6.])

In [97]:
#Bool -> Int -> Float -> String
a.dtype

dtype('float64')


# Linspace

In [98]:
np.linspace(10,50,5) # Linspace(Start, Stop, Number of elements) - E

array([ 10.,  20.,  30.,  40.,  50.])

In [99]:
np.linspace(150,200,5)

array([ 150. ,  162.5,  175. ,  187.5,  200. ])

In [100]:
np.linspace(200,300,5)

array([ 200.,  225.,  250.,  275.,  300.])

In [101]:
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

### Create a 6 dimensional data with arange having 6 elements in 1 dimension

In [136]:
e = np.arange(192).reshape(2,2,2,2,2,6)

In [133]:
np.arange(6).reshape(1,1,1,1,1,6)

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

# Ravel

In [122]:
d = d.ravel()
d

array([0, 1, 2, 3, 4, 5])

In [127]:
e = [1,2,3,4,5]

In [137]:
e = e.ravel()
e

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [224]:
int(np.random.rand()*100)

76

In [226]:
np.random.rand(5,3)

array([[ 0.13613651,  0.94167047,  0.33034977],
       [ 0.76279504,  0.80372019,  0.32204978],
       [ 0.86819318,  0.16992257,  0.12897396],
       [ 0.09189934,  0.80334608,  0.51060316],
       [ 0.65413913,  0.0866613 ,  0.78698948]])

In [153]:
np.sqrt(np.random.randint(35,100,50).reshape(5,10))

array([[ 6.55743852,  7.41619849,  9.21954446,  5.91607978,  6.164414  ,
         7.07106781,  9.79795897,  7.74596669,  6.244998  ,  8.54400375],
       [ 8.60232527,  9.05538514,  9.59166305,  6.4807407 ,  9.79795897,
         8.54400375,  8.30662386,  9.05538514,  6.08276253,  6.164414  ],
       [ 9.05538514,  7.68114575,  8.        ,  9.32737905,  8.66025404,
         7.74596669,  9.32737905,  7.87400787,  7.34846923,  8.66025404],
       [ 7.61577311,  7.87400787,  7.34846923,  8.1240384 ,  6.08276253,
         6.63324958,  8.48528137,  7.41619849,  7.28010989,  9.32737905],
       [ 7.87400787,  9.79795897,  9.2736185 ,  7.68114575,  8.66025404,
         9.48683298,  7.74596669,  6.63324958,  7.68114575,  8.06225775]])

In [159]:
print(np.round(5.5)) # Does a round
print(np.floor(5.5)) # Does the lowest round
print(np.ceil(5.5)) #Does the highest round

6.0
5.0
6.0


In [161]:
f = np.arange(24).reshape(4,6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [181]:
np.hsplit(f,2) # Split the array horizontally

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [179]:
np.vsplit(f,4) # Split the array vertically

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]])]

# Horizontal and Vertical Stack

In [188]:
f = np.arange(9).reshape(3,3)
g = np.arange(20,29).reshape(3,3)
print(f)
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [194]:
np.vstack((f,g))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [189]:
np.hstack((f,g))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28]])

# Q: Add Two integers into an array and typecast it to float

In [220]:
h = np.random.randn(5,10,2)
h = h[0] + h[1]
h

array([[ 1.3431918 ,  1.82873352],
       [ 2.79493932, -2.52767963],
       [ 0.22548001, -1.51572249],
       [ 0.44706382, -1.79402726],
       [ 2.42172625,  1.97140799],
       [ 2.30623747,  4.92487971],
       [ 3.28264508,  0.40019743],
       [ 0.68869244,  2.85145749],
       [ 2.34434022,  1.16779632],
       [ 1.70308931, -0.68776474]])

In [216]:
h = np.array([2+3,4+5],dtype='float')
print(h)
print(h.dtype)

[ 5.  9.]
float64
